site_name: Beam Docs
site_url: https://example.com/
nav:
    - Home: index.md
    - Getting Started: start.md
    - User Guide: user_guide.md
        - Beam Module: ./user_guide/beam_module.md
        - Beam Sentry: ./user_guide/beam_sentry.md
        - Beam Manager: ./user_guide/beam_manager.md
        - Octo Beam: ./user_guide/beam_octo.md
    - Developer Guide: dev_guide.md
        - Beam Source Code: ./dev_guide/beam_source_code.md
    - About: about.md