site_name: Beam Docs
site_url: https://example.com/
nav:
    - Home: index.md
    - QuickStart: start.md
    - FAQ: FAQ.md
    - API&OctoBeam: beam-octo.md


markdown_extensions:
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css